name: Update Azure VM

on:
  push:
    branches:
      - main

jobs:
  update-vm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update Azure VM
      run: |
        # Log in using the Azure credentials
        echo ${{ secrets.AZURE_CREDENTIALS }} > /tmp/azure_credentials.json
        az login --identity --allow-no-subscriptions

        # Replace 'resource_group', 'vm_name', and 'path/to/repo/on/vm' with your actual values
        az vm run-command invoke -g resource_group -n vm_name --command-id RunShellScript --scripts "cd path/to/repo/on/vm && git pull"

      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
